Casual Roster Web/Models/Teacher/TeacherViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Casual_Roster_Web.Models
{


    [FluentValidation.Attributes.Validator(typeof(Validators.TeacherViewValidator))]
    // this model will be used in all teacher forms
    // add necessary fields, just add ruleset to isolate required fields
    public class TeacherViewModel : Casual_Roster.TeacherProfileTable
    {

        // convert view model to table model
        public Casual_Roster.TeacherProfileTable ToProfile()
        {

            Casual_Roster.LocationTable loc = null;
            if(this.lat != null && this.lng != null) {
                loc = new Casual_Roster.LocationTable()
                {
                    lat = (decimal)this.lat,
                    lng = (decimal)this.lng,
                    formattedAddress = this.formattedAddress
                };
            }

            return new Casual_Roster.TeacherProfileTable()
            {
                user_id = this.user_id,
                User = this.User,
                firstName = this.firstName,
                lastName = this.lastName,
                gender = this.gender,
                email = this.email,
                mobile = this.mobile,
                mobileAlter = this.mobileAlter,
                mobileCountryCode = this.mobileCountryCode,
                postCode = this.postCode,
                category = this.category,
                preferredSchools = this.preferredSchools,
                Location = loc
            };
        }

        public void FromProfile(Casual_Roster.TeacherProfileTable profile)
        {
            if (profile == null) return;
            this.user_id = profile.user_id;
            this.User = profile.User;
            this.firstName = profile.firstName;
            this.lastName = profile.lastName;
            this.gender = profile.gender;
            this.email = profile.email;
            this.mobile = profile.mobile;
            this.mobileAlter = profile.mobileAlter;
            this.mobileCountryCode = profile.mobileCountryCode;
            this.postCode = profile.postCode;
            this.category = profile.category;
            this.preferredSchools = profile.preferredSchools;
            this.PhotoData = profile.PhotoData;
            if (profile.Location != null)
            {
                this.lat = profile.Location.lat;
                this.lng = profile.Location.lng;
                this.formattedAddress = profile.Location.formattedAddress;
            }
            
        }


        public decimal? lat { get; set; }
        public decimal? lng { get; set; }

        public string password_repeat { get; set; }

        public string formattedAddress { get; set; }



    }

}

Casual Roster Web/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using Casual_Roster;
using Casual_Roster_Web.Models;
using FluentValidation.Mvc;

namespace Casual_Roster_Web.Controllers
{
    public class TeacherController : Controller
    {

        public ActionResult Register()
        {
            var teacher = new Casual_Roster.TeacherProfileTable();
            var teacherView = new TeacherViewModel();
            teacher.mobileCountryCode = System.Globalization.RegionInfo.CurrentRegion.TwoLetterISORegionName;
            teacherView.FromProfile(teacher);

            ViewBag.categoriesSelectList = new SelectList(
                Teacher.Categories.Select(x =>
                    new KeyValuePair<String, String>(x, x)
                    )
                , "Key", "Value"
            );
            return View(teacherView);
        }


        [HttpPost]
        public ActionResult Register([CustomizeValidator(RuleSet = "default,RegisterTeacher")] TeacherViewModel teacherViewModel, HttpPostedFileBase uploadedLogo)
        {

            if (!ModelState.IsValid)
            {

                // categories selectlist box
                ViewBag.categoriesSelectList = new SelectList(
                    Teacher.Categories.Select(x =>
                        new KeyValuePair<String, String>(x, x)
                        )
                    , "Key", "Value", teacherViewModel.category);
                return View("Register", teacherViewModel);
            }

            teacherViewModel.mobileCountryCode = System.Globalization.RegionInfo.CurrentRegion.TwoLetterISORegionName;
            var teacher = teacherViewModel.ToProfile();
            Casual_Roster.Teacher.Register(teacher);
            if (uploadedLogo != null)
            {
                new Casual_Roster.Teacher(teacher.user_id).UpdatePhoto(uploadedLogo, Server);
            }

            return RedirectToAction("Login", "Account");
        }

        public ActionResult RegisterRequested(int id)
        {
            var teacherData = Casual_Roster.School.GetRequestTeacherData(id);
            if (teacherData != null)
            {
                // if teacher is already registered
                if (teacherData.has_registered)
                {
                    return HttpNotFound();
                }
                var teacher = new Casual_Roster.Teacher(id).Profile;
                teacher.mobileCountryCode = System.Globalization.RegionInfo.CurrentRegion.TwoLetterISORegionName;
                
                // cast to view object
                var viewModel = new Models.TeacherViewModel();
                viewModel.FromProfile(teacher);
                return View(viewModel);
            }
            return HttpNotFound();
            
        }

        [HttpPost]
        public ActionResult RegisterRequested([CustomizeValidator(RuleSet = "Username,Password,RegisterRequested")] Models.TeacherViewModel teacher, int id, HttpPostedFileBase uploadedLogo)
        {
            teacher.user_id = id;
            // if teacher is already registered
            if (Casual_Roster.School.GetRequestTeacherData(id).has_registered)
            {
                return HttpNotFound();
            }

            if (!ModelState.IsValid)
            {
                return View("RegisterRequested", teacher);
            }

            Casual_Roster.Teacher.UpdateRequested(teacher.ToProfile());
            // update photo
            if(uploadedLogo != null) {
                new Casual_Roster.Teacher(teacher.user_id).UpdatePhoto(uploadedLogo, Server);
            }

            return RedirectToAction("Login", "Account");
        }



        #region Avalabilities

        [Authorize(Roles="teacher")]
        public ActionResult Availability(string startDate)
        {
            var emailUsername = System.Web.HttpContext.Current.User.Identity.Name;
            var user = Casual_Roster.User.GetUser(emailUsername: emailUsername);
            ViewBag.userId = user.ID;
            ViewBag.date = startDate ?? "";
            return View();
        }


        [Authorize]
        public ActionResult jsonAvailabilities(int teacherId, int week, int year)
        {
            var teacher = new Casual_Roster.Teacher(teacherId);

            return Json(new
            {
                availabilities = teacher.GetAvailabilities(week, year)
            }, JsonRequestBehavior.AllowGet);
        }


        [Authorize(Roles="teacher")]
        [HttpPost]
        public ActionResult SaveAvailabilities(int[] daysAvailable, int week, int year)
        {
            var user = Casual_Roster.User.GetUser(emailUsername: System.Web.HttpContext.Current.User.Identity.Name);
            var teacher = new Casual_Roster.Teacher(user.ID);
            teacher.SaveAvailabilities(daysAvailable, week, year);
            return Json(new {  });
        }

        #endregion


        [HttpPost]
        [Authorize]
        public ActionResult GetRosterRequests(DateTime date)
        {
            var user = Casual_Roster.User.GetUser(emailUsername: System.Web.HttpContext.Current.User.Identity.Name);
            return Json(new
            {
                requests = Casual_Roster.Roster.GetRequestsForDay(date, teacherId: user.ID).ToArray()
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles="teacher")]
        public ActionResult RosterAction(int rosterId) 
        {
            var roster = new Casual_Roster.Roster(rosterId);
            if (Casual_Roster.User.GetUser(emailUsername: System.Web.HttpContext.Current.User.Identity.Name).ID != roster.Teacher.id)
            {
                return HttpNotFound();
            }
            ViewBag.roster = roster;
            return View();
        }

        [Authorize(Roles = "teacher")]
        public ActionResult AcceptRoster(int id)
        {
            // TODO check if current teacher is what on the roster request
            new Casual_Roster.Roster(id).UpdateStatus(Casual_Roster.Roster.Statuses.Approved);
            return RedirectToAction("Availability");
        }

        [Authorize(Roles = "teacher")]
        public ActionResult DeclineRoster(int id)
        {
            // TODO check if current teacher is what on the roster request
            new Casual_Roster.Roster(id).UpdateStatus(Casual_Roster.Roster.Statuses.Declined);
            return RedirectToAction("Availability");
        }


        public ActionResult Profile(int id)
        {
            return View(new Casual_Roster.Teacher(id));
        }


        [Authorize(Roles="teacher")]
        public ActionResult EditProfile()
        {
            // always current user is editing his profile
            var user = Casual_Roster.User.GetUser(emailUsername: System.Web.HttpContext.Current.User.Identity.Name);
            var viewModel = new Models.TeacherViewModel();
            viewModel.FromProfile( new Casual_Roster.Teacher(user.ID).Profile );
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "teacher")]
        public ActionResult EditProfile([CustomizeValidator(RuleSet = "EditProfile")] Models.TeacherViewModel teacher, HttpPostedFileBase uploadedLogo)
        {
            // always current user is editing his profile
            var user = Casual_Roster.User.GetUser(emailUsername: System.Web.HttpContext.Current.User.Identity.Name);
            var _teacher = new Casual_Roster.Teacher(user.ID);

            if (!ModelState.IsValid)
            {
                teacher.FromProfile(_teacher.Profile);
                return View(teacher);
            }

            // udpate the profile
            _teacher.UpdateProfile(teacher.ToProfile());
            if (uploadedLogo != null)
            {
                _teacher.UpdatePhoto(uploadedLogo, Server);
            }

            ViewBag.success = true;
            teacher.FromProfile(_teacher.Profile);
            return View(teacher); // TODO improve this not to reinit
        }


        [Authorize(Roles="teacher")]
        public ActionResult jsonGetSchoolsAvailable(string ids = "")
        {
            var user = Casual_Roster.User.GetUser(emailUsername: System.Web.HttpContext.Current.User.Identity.Name);
            var schools = Casual_Roster.School.GetAvailableSchoolsForTeacher(user.ID)
                .Where(t =>
                {
                    // for initselection of select2
                    // ids param is passed
                    if (ids != "")
                    {
                        return ids.Split(',').Contains(t.id + "");
                    }

                    return true;
                })
                // hide not required fields
                .Select(t =>
                {
                    var profile = t.Profile;
                    return new
                    {
                        id = t.id,
                        schoolName = profile.schoolName
                    };
                });

            return Json(new
            {
                schools = schools
            }, JsonRequestBehavior.AllowGet);
        }


        [Authorize]
        public ActionResult jsonGetMobileInfo(string mobile, string countryCode)
        {
            var teacher = Casual_Roster.Teacher.GetByMobile(mobile, countryCode);

            if (teacher == null)
            {
                return HttpNotFound();
            }

            return Json(new
            {
                teacher = new
                {
                    user_id = teacher.user_id,
                    mobile = teacher.mobile,
                    firstName = teacher.firstName,
                    lastName = teacher.lastName,
                    email = teacher.email,
                    postCode = teacher.postCode,
                    category = teacher.category
                }
            }, JsonRequestBehavior.AllowGet);
        }

Casual Roster Web/Views/Teacher/EditProfile.cshtml
@model Casual_Roster_Web.Models.TeacherViewModel
@{
    ViewBag.Title = "Edit Profile";
}

@section scripts {

    <script src='http://maps.googleapis.com/maps/api/js?v=3&sensor=false&amp;libraries=places'></script>
    @Scripts.Render("~/Content/geocomplete")
    @Scripts.Render("~/bundles/select2")
    @Scripts.Render("~/bundles/intltelinput")

    <script>
        $(function() {

            function formatter(data) {
                return {
                    results: _.map(data.schools, function(school) {
                        return {
                            text: school.schoolName,
                            id: school.id
                        }
                    })
                };
            }

            $('#preferredSchools').select2({
                placeholder: 'Select preffered schools',
                multiple: true,
                initSelection: function(element, callback) {
                    return $.getJSON( "@Url.Content("~/Teacher/jsonGetSchoolsAvailable")?ids=" + element.val(), null, function(data) {
                        if(!data) return;

                        // remove not valid ids
                        var selectedIds = _.pluck(data.schools, 'id');
                        selectedIds = selectedIds.join(',');
                        $('#preferredSchools').val( selectedIds );

                        return callback(
                            _.map(data.schools, function(school) {
                                return {
                                    text: school.schoolName,
                                    id: school.id
                                };
                            })
                        );
                    });
                },

                ajax: {
                    url: "@Url.Content("~/Teacher/jsonGetSchoolsAvailable")",
                    dataType: 'json',
                    results: function(data) {
                        return formatter(data);
                    }
                }
            });



            // location
            var params = {
                map: '.map'
            };

            var geoMap = $('#formattedAddress').geocomplete(params)

            geoMap.bind("geocode:result", function(event, result){
                if(result) {
                    $('#lat').val( result.geometry.location.lat() );
                    $('#lng').val( result.geometry.location.lng() );
                }
            });

            @if(Model.lat != null && Model.lng != null) {
                <text>
                    $('#formattedAddress').geocomplete("find", "@Model.formattedAddress");
                </text>
            }

        });
    </script>
}

@section styles {
    @Styles.Render("~/Content/select2Css")
    @Styles.Render("~/bundles/intltelinputCss")
}



<div class="row">
    
    @using (Html.BeginForm("EditProfile", "Teacher", FormMethod.Post, new { enctype = "multipart/form-data" } )) {


        <div class="col-md-12 clearfix">

            @if(!ViewData.ModelState.IsValid) {
                <div class="alert alert-danger">@Html.ValidationSummary()</div>
            }   

            @if(ViewBag.success != null) {
                <div class="alert alert-success">Profile successfully updated</div>
            }

            <h1 class="pull-left">@ViewBag.Title</h1>
            <button type="button" class="pull-right btn btn-success form-submit">Update Profile</button>

        </div>

        @Html.HiddenFor(x => x.mobileCountryCode )
        @Html.HiddenFor(x => x.user_id )


        <div class="clearfix">

            <div class="col-md-3">
                <div class="teacher-photo" style="background-image: url(@Url.Content("~/Content/uploads")/@(Model.PhotoData != null ? Model.PhotoData.filename : ""))"></div>
                <div class="form-group">
                    <label>Change Photo</label>
                    <input type="file" name="uploadedLogo">
                    <!--<p class="help-block">Example block-level help text here.</p>-->
                </div>
            </div>


            <div class="col-md-5">
                <div class="form-group">
                    @Html.LabelFor(x => x.firstName )
                    @Html.TextBoxFor(x => x.firstName, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(x => x.firstName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.lastName )
                    @Html.TextBoxFor(x => x.lastName, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(x => x.lastName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.gender )
                    <div>
                        <label>
                            @Html.RadioButtonFor(x => x.gender, "Male")
                            Male
                        </label>
                        <label>
                            @Html.RadioButtonFor(x => x.gender, "Female")
                            Female
                        </label>
                    </div>
                    @Html.ValidationMessageFor(x => x.gender)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.email )
                    @Html.TextBoxFor(x => x.email, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(x => x.email)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.mobile )
                    @Html.TextBoxFor(x => x.mobile, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(x => x.mobile)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.mobileAlter )
                    @Html.TextBoxFor(x => x.mobileAlter, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(x => x.mobileAlter)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.category )
                    @Html.TextBoxFor(x => x.category, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(x => x.category)
                </div>
            </div> 


            <div class="col-md-4">

                <div class="form-group">
                    @Html.LabelFor(x => x.preferredSchools )
                    @Html.HiddenFor(x => x.preferredSchools )
                    @Html.ValidationMessageFor(x => x.preferredSchools)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.postCode )
                    @Html.TextBoxFor(x => x.postCode, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(x => x.postCode)
                </div>

                <div class="form-group">
                    <label for="formattedAddress">Location</label>
                    @Html.TextBoxFor(x => x.formattedAddress, new { @class = "form-control" } )
                    @Html.HiddenFor(x => x.lat)
                    @Html.HiddenFor(x => x.lng)
                    <div class="panel">
                        <div class="map"></div>
                    </div>
                </div>

            </div>
        </div>


    }
</div>

Casual Roster Web/Views/Teacher/Profile.cshtml
@model Casual_Roster.Teacher


@{
    ViewBag.Title = Model.Profile.firstName + " - Casual Roster";
    var profile = Model.Profile;
}


<div class="col-md-3 col-sm-5 col-xs-12">

    <div class="teacher-photo" style="background-image: url(@Url.Content("~/Content/uploads")/@(profile.PhotoData != null ? profile.PhotoData.filename : ""))"></div>


</div>


<div class="col-md-4 col-sm-7 col-xs-12 profile-body">
    @if(ViewBag.CurrentUser != null && ViewBag.CurrentUser.GetProfile().user_id == profile.user_id) {
        <a href="@Url.Content("~/Teacher/EditProfile")" class="btn btn-primary pull-right btn-sm">Edit profile</a>
    }

    <h1>@profile.firstName</h1>
    <p><label>Name: </label> <b>@profile.firstName @profile.lastName</b></p>
    <p><label>Gender: </label> <b>@profile.gender</b></p>
    <hr />
    <p><label>Category: </label> <b>@profile.category</b></p>
    <p><label>Email: </label> <b>@profile.email</b></p>
    <p><label>Mobile: </label> <b>@profile.mobile</b></p>
    <p><label>Mobile (alternative): </label><b>@profile.mobileAlter</b></p>
    <p><label>Post code: </label> <b>@profile.postCode</b></p>
</div>

<div class="col-md-4 col-sm-12 col-xs-12 map-container">
    @if(profile.Location != null) {
        <p>@profile.Location.formattedAddress</p>
        <img src="https://maps.googleapis.com/maps/api/staticmap?center=@profile.Location.lat,@profile.Location.lng&zoom=14&size=400x300&markers=icon:xxx%7Cshadow:true%7C@(profile.Location.formattedAddress)">
    }
</div>

Casual Roster Web/Views/Teacher/Register.cshtml
@model Casual_Roster_Web.Models.TeacherViewModel


@{
    ViewBag.Title = "Temp Registration";
}


@section scripts {
    @Scripts.Render("~/bundles/intltelinput")
}

@section styles {
    @Styles.Render("~/bundles/intltelinputCss")
}


<div class="col-md-5">
    <h1>Temp Registration</h1>
    @using (Html.BeginForm("Register", "Teacher", FormMethod.Post, new { enctype = "multipart/form-data" } )) {

        @Html.HiddenFor(x => x.mobileCountryCode )

        <div class="form-group">
            @Html.LabelFor(x => x.firstName )
            @Html.TextBoxFor(x => x.firstName, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.firstName)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.lastName )
            @Html.TextBoxFor(x => x.lastName, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.lastName)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.gender )
            <div>
                <label>
                    Male
                    @Html.RadioButtonFor(x => x.gender, "Male")
                </label>
                <label>
                    Female
                    @Html.RadioButtonFor(x => x.gender, "Female")
                </label>
            </div>
            @Html.ValidationMessageFor(x => x.gender)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.email )
            @Html.TextBoxFor(x => x.email, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.email)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.mobile )
            @Html.TextBoxFor(x => x.mobile, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.mobile)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.mobileAlter )
            @Html.TextBoxFor(x => x.mobileAlter, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.mobileAlter)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.postCode )
            @Html.TextBoxFor(x => x.postCode, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.postCode)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.User.username )
            @Html.TextBoxFor(x => x.User.username, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.User.username)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.User.password )
            @Html.PasswordFor(x => x.User.password, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.User.password)
        </div>

        <div class="form-group">
            <label>Repeat Password</label>
            @Html.PasswordFor(x => x.password_repeat, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.password_repeat)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.category )
            @Html.DropDownListFor(m => m.category, (SelectList)ViewBag.categoriesSelectList, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.category)
        </div>

        <div class="form-group">
            <label>Photo</label>
            <input type="file" name="uploadedLogo" class="btn btn-default">
            <!--<p class="help-block">Example block-level help text here.</p>-->
        </div>

        <button type="button" class="btn btn-success btn-lg form-submit">Submit</button>
    }   
</div>


<div class="col-md-5">
    @if(!ViewData.ModelState.IsValid) {
        <div class="alert alert-danger">
            @Html.ValidationSummary()
        </div>
    }
</div>

Casual Roster Web/Views/Teacher/RegisterRequested.cshtml
@model Casual_Roster_Web.Models.TeacherViewModel


@{
    ViewBag.Title = "Register Requested Temp";
}


@section scripts {
    @Scripts.Render("~/bundles/intltelinput")
}

@section styles {
    @Styles.Render("~/bundles/intltelinputCss")
}



<div class="col-md-5">
    <h1>@ViewBag.Title</h1>
    @using (Html.BeginRouteForm("QueryRoute", new{ action="RegisterRequested", controller="Teacher", id=Model.user_id }, FormMethod.Post, new { enctype = "multipart/form-data" })) {

        @Html.HiddenFor(x => x.User.ID)
        @Html.HiddenFor(x => x.user_id)
        @Html.HiddenFor(x => x.mobileCountryCode)

        <div class="form-group">
            @Html.LabelFor(x => x.firstName )
            @Html.TextBoxFor(x => x.firstName, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.firstName)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.lastName )
            @Html.TextBoxFor(x => x.lastName, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.lastName)
        </div>
        
        <div class="form-group">
            @Html.LabelFor(x => x.gender )
            <div>
                <label>
                    Male
                    @Html.RadioButtonFor(x => x.gender, "Male")
                </label>
                <label>
                    Female
                    @Html.RadioButtonFor(x => x.gender, "Female")
                </label>
            </div>
            @Html.ValidationMessageFor(x => x.gender)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.email )
            @Html.TextBoxFor(x => x.email, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.email)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.mobile )
            @Html.TextBoxFor(x => x.mobile, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.mobile)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.mobileAlter )
            @Html.TextBoxFor(x => x.mobileAlter, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.mobileAlter)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.postCode )
            @Html.TextBoxFor(x => x.postCode, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.postCode)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.User.username )
            @Html.TextBoxFor(x => x.User.username, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.User.username)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.User.password )
            @Html.PasswordFor(x => x.User.password, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.User.password)
        </div>

        <div class="form-group">
            <label>Photo</label>
            <input type="file" name="uploadedLogo" class="btn btn-default">
            <!--<p class="help-block">Example block-level help text here.</p>-->
        </div>


        <button type="button" class="btn btn-success btn-lg form-submit">Submit</button>
    }   
</div>



<div class="col-md-5">
    @if(!ViewData.ModelState.IsValid) {
        <div class="alert alert-danger">
            @Html.ValidationSummary()
        </div>
    }
</div>

Casual Roster Web/Views/Teacher/RosterAction.cshtml
@{
    ViewBag.Title = "Roster Action";
}


<div class="col-md-6 col-md-offset-3 text-center">
	<h1>Casual Roster Alert</h1>

	<p>School: @ViewBag.roster.School.Profile.schoolName</p>
	<p>Contact: @ViewBag.roster.School.Profile.phones</p>
	<p>Required Date: @ViewBag.roster.Request.roster_date.ToString("ddd dd MMM yyyy")</p>

	<div class="panel">
		<div class="col-md-6 col-md-offset-3">
			<a href="@Url.Content("~/Teacher/AcceptRoster")?id=@ViewBag.roster.id" onclick="return confirm('Continue accepting roster request?')" class="btn btn-success btn-block">Accept</a>
			<a href="@Url.Content("~/Teacher/DeclineRoster")?id=@ViewBag.roster.id" onclick="return confirm('Continue declining roster request?')" class="btn btn-danger btn-block">Decline</a>
		</div>
	</div>
</div>