Casual Roster Web/Models/School/SchoolViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Casual_Roster;

namespace Casual_Roster_Web.Models
{


    [FluentValidation.Attributes.Validator(typeof(Validators.SchoolViewValidator))]
    // this model will be used in all teacher forms
    // add necessary fields, just add ruleset to isolate required fields
    public class SchoolViewModel : Casual_Roster.SchoolProfileTable
    {

        // convert view model to table model
        public Casual_Roster.SchoolProfileTable ToProfile()
        {
            string _phones = "";
            Casual_Roster.LocationTable location = null;
            UserTable _user = this.User;
            if (this.phones != null)
            {
                _phones = this.phones;
            }
            if (this.lat != null && this.lng != null)
            {
                location = new Casual_Roster.LocationTable()
                {
                    lat = (decimal) this.lat,
                    lng = (decimal) this.lng,
                    formattedAddress = this.formattedAddress
                };
            }

            return new Casual_Roster.SchoolProfileTable()
            {
                User = _user,
                user_id = this.user_id,
                schoolName = this.schoolName,
                email = this.email,
                mobile = this.mobile,
                phones = _phones,
                mobileCountryCode = this.mobileCountryCode,
                postCode = this.postCode,
                LogoData = this.LogoData,
                Location = location
            };
        }

        public void FromProfile(Casual_Roster.SchoolProfileTable profile)
        {
            if (profile == null) return;
            this.user_id = profile.user_id;
            this.schoolName = profile.schoolName;
            this.phones = profile.phones;
            this.email = profile.email;
            this.mobile = profile.mobile;
            this.mobileCountryCode = profile.mobileCountryCode;
            this.postCode = profile.postCode;
            this.LogoData = profile.LogoData;
            if (profile.Location != null)
            {
                this.lat = profile.Location.lat;
                this.lng = profile.Location.lng;
                this.formattedAddress = profile.Location.formattedAddress;
            }
            
        }


        public decimal? lat { get; set; }
        public decimal? lng { get; set; }

        public string password_repeat { get; set; }

        public string formattedAddress { get; set; }



    }

}

Casual Roster Web/Models/School/SchoolViewValidator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FluentValidation;
using FluentValidation.Results;

namespace Casual_Roster_Web.Validators
{
    public class SchoolViewValidator : AbstractValidator<Casual_Roster_Web.Models.SchoolViewModel>
    {

        public SchoolViewValidator()
        {

            RuleSet("Register", () =>
            {
                RuleFor(x => x.schoolName).NotEmpty();
                RuleFor(x => x.address).NotEmpty();
                RuleFor(x => x.email).NotEmpty().EmailAddress();
                RuleFor(x => x.mobile).NotEmpty();
                RuleFor(x => x.postCode).NotEmpty();
                RuleFor(x => x.User.password).NotEmpty();
                RuleFor(x => x.password_repeat).NotEmpty().WithMessage("Repeat password must have a value");

                Custom(x =>
                {
                    if (x.password_repeat != x.User.password)
                    {
                        return new ValidationFailure("password_repeat", "Password does not match");
                    }
                    return null;
                });

                // check if mobile is valid
                Custom(x =>
                {
                    bool valid = Casual_Roster.User.mobileIsValid(x.mobile, x.mobileCountryCode);
                    if (!valid)
                        return new ValidationFailure("mobile", "Mobile number is invalid. Do not include country code");
                    return null;
                });

                // check if mobile exists
                Custom(x =>
                {
                    bool existing = Casual_Roster.User.mobileExists(x.mobile, x.mobileCountryCode, x.user_id);
                    if (existing)
                        return new ValidationFailure("mobile", "Mobile number is already in use.");
                    return null;
                });


            });




            RuleSet("EditProfile", () =>
            {
                RuleFor(x => x.schoolName).NotEmpty();
                RuleFor(x => x.email).NotEmpty().EmailAddress();
                RuleFor(x => x.mobile).NotEmpty();
                RuleFor(x => x.postCode).NotEmpty();

                Custom(x =>
                {
                    bool noLocation = x.lat == null || x.lng == null || x.formattedAddress == null;
                    if (noLocation)
                        return new ValidationFailure("formattedAddress", "Location must have a value");
                    return null;
                });

                Custom(x =>
                {
                    // TODO maybe get the user here? for security. as of now id is just included in the form
                    bool existing = Casual_Roster.User.EmailExists(x.email, x.user_id);
                    if (existing)
                        return new ValidationFailure("email", "Email address is already in use");
                    return null;
                });

                // check if mobile is valid
                Custom(x =>
                {
                    bool valid = Casual_Roster.User.mobileIsValid(x.mobile, x.mobileCountryCode);
                    if (!valid)
                        return new ValidationFailure("mobile", "Mobile number is invalid. Do not include country code.");
                    return null;
                });

                // check if mobile exists
                Custom(x =>
                {
                    bool existing = Casual_Roster.User.mobileExists(x.mobile, x.mobileCountryCode, x.user_id);
                    if (existing)
                        return new ValidationFailure("mobile", "Mobile number is already in use.");
                    return null;
                });

            });
        }

    }
}

Casual Roster Web/Controllers/SchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Casual_Roster;
using Casual_Roster_Web.Models;
using FluentValidation.Mvc;
using Newtonsoft.Json.Linq;

namespace Casual_Roster_Web.Controllers
{
    public class SchoolController : Controller
    {

        public ActionResult Register()
        {
            var school = new Casual_Roster.SchoolProfileTable();
            school.mobileCountryCode = System.Globalization.RegionInfo.CurrentRegion.TwoLetterISORegionName;
            //ViewBag.countryCodes = Casual_Roster.Utils.GetSelectListCountries();
            var schoolModel = new SchoolViewModel();
            schoolModel.FromProfile(school);
            return View(schoolModel);
        }

        
        [HttpPost]
        public ActionResult Register([CustomizeValidator(RuleSet = "Register")] Casual_Roster_Web.Models.SchoolViewModel school, HttpPostedFileBase uploadedLogo)
        {
            if (!ModelState.IsValid)
            {
                return View("Register", school);
            }

            Casual_Roster.School.Register(school.ToProfile());
            var createdSchool = new Casual_Roster.School(school.user_id);
            return RedirectToAction("Roster");
        }


        public ActionResult AddTeacher()
        {
            var user = Casual_Roster.User.GetUser(emailUsername: System.Web.HttpContext.Current.User.Identity.Name);
            var teacher = new Teacher(user.ID);
            return View(new TeacherViewModel()
            {
                mobileCountryCode = teacher.Profile != null ? teacher.Profile.mobileCountryCode : System.Globalization.RegionInfo.CurrentRegion.TwoLetterISORegionName
            });
        }

        
        [HttpPost]
        [Authorize(Roles = "school")]
        public ActionResult AddTeacher([CustomizeValidator(RuleSet = "RequestTeacher")] Models.TeacherViewModel teacher, int teacherId = 0)
        {
            var school = Casual_Roster.User.GetUser(emailUsername: System.Web.HttpContext.Current.User.Identity.Name);
            // mobile is selected
            if (teacherId != 0)
            {
                // selected teacher via mobile is a existing user
                Casual_Roster.School.RequestExistingTeacher(teacherId, school.ID);
                return RedirectToAction("Roster");
                
            } 
            else if (!ModelState.IsValid)
            {
                return View("AddTeacher", teacher);
            }
            
            teacher.mobileCountryCode = System.Globalization.RegionInfo.CurrentRegion.TwoLetterISORegionName;
            Casual_Roster.School.RequestTeacher(teacher.ToProfile(), school.ID);

            return RedirectToAction("Roster");
        }


        [Authorize(Roles = "school")]
        public ActionResult EditProfile()
        {
            // always current user is editing his profile
            var user = Casual_Roster.User.GetUser(emailUsername: System.Web.HttpContext.Current.User.Identity.Name);
            var viewModel = new Models.SchoolViewModel();
            viewModel.FromProfile(new Casual_Roster.School(user.ID).Profile);
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "school")]
        public ActionResult EditProfile([CustomizeValidator(RuleSet = "EditProfile")] Models.SchoolViewModel school, HttpPostedFileBase uploadedLogo)
        {

            // always current user is editing his profile
            var user = Casual_Roster.User.GetUser(emailUsername: System.Web.HttpContext.Current.User.Identity.Name);
            var _school = new Casual_Roster.School(user.ID);            

            if (!ModelState.IsValid)
            {
                school.FromProfile(_school.Profile);
                return View(school);
            }

            // udpate the profile
            _school.UpdateProfile(school.ToProfile());
            if (uploadedLogo != null)
            {
                _school.UpdateLogo(uploadedLogo, Server);
            }

            ViewBag.success = true;
            school.FromProfile(_school.Profile);
            return View(school); // TODO improve this not to reinit
        }



        [Authorize(Roles="school")]
        public ActionResult Roster(string startDate)
        {
            ViewBag.date = startDate ?? "";
            return View();
        }


        [Authorize]
        public ActionResult GetStaff(int year, int month, int day)
        {
            DateTime d = new DateTime();

            try
            {
                // if date is invalid
                d = new DateTime(year, month, day);
            } catch(Exception) {
                return HttpNotFound();
            }

            // TODO add method for getting current user
            var user = Casual_Roster.User.GetUser(emailUsername: System.Web.HttpContext.Current.User.Identity.Name);
            ViewBag.schoolId = user.ID;
            ViewBag.requestDate = d;
            // exclude teachers who are already requested
            ViewBag.availableTeachers = (IList<Casual_Roster.Teacher>)Casual_Roster.Teacher.GetAvailableIn(d).ToList();
            //ViewBag.availableTeachers = (IList<Casual_Roster.Teacher>)Casual_Roster.Teacher.GetAll().ToList();
            
            return View();
        }


        [HttpPost]
        public ActionResult RosterRequest(int[] teacherIds, int schoolId, DateTime rosterDate)
        {
            List<String> errors = new List<String>();
            if (teacherIds == null || schoolId == null || rosterDate == null)
            {
                errors.Add("Invalid parameters");
            }


            foreach (var teacherId in teacherIds)
            {
                // todo validate if teacher is available
                var teacher = new Casual_Roster.Teacher(teacherId);
                Casual_Roster.Roster roster = new Casual_Roster.Roster(
                    teacher,
                    new Casual_Roster.School(schoolId),
                    rosterDate
                );

                try
                {
                    roster.Save();
                }
                catch (Exception)
                {
                    errors.Add("You already requested " + teacher.Profile.firstName);
                }
            }

            return Json( new {
                success = errors.Count == 0,
                errors = errors.ToArray()
            } );
        }

        [HttpPost]
        [Authorize]
        public ActionResult GetRosterRequests(int week)
        {
            var user = Casual_Roster.User.GetUser(emailUsername: System.Web.HttpContext.Current.User.Identity.Name);
            var requests = Casual_Roster.Roster.GetRequestsInWeek(week, user.ID);
            List<dynamic> ret = new List<dynamic>();

            // remove recursive data
            foreach (var req in requests)
            {
                ret.Add(
                    new
                    {
                        RosterDateUnix = req.RosterDateUnix,
                        id = req.id,

                        Teacher = new
                        {
                            id = req.Teacher.id,
                            Profile = new
                            {
                                firstName = req.Teacher.Profile.firstName,
                                lastName = req.Teacher.Profile.lastName,
                                photo = (req.Teacher.Profile.PhotoData != null ? req.Teacher.Profile.PhotoData.filename : "")
                            }
                        },

                        School = new {
                            id = req.School.id,
                            Logo = req.School.Logo,
                            Profile = new
                            {
                                schoolName = req.School.Profile.schoolName
                            }
                        },

                        Request = new
                        {
                            ID = req.Request.ID,
                            roster_date = req.Request.roster_date,
                            status = req.Request.status
                        }
                    }
                );
            }

            return Json(new
            {
                //test = System.Globalization.RegionInfo.CurrentRegion.TwoLetterISORegionName,
                requests = ret.ToArray()
            }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Profile(int id)
        {
            var school = new Casual_Roster.School(id);
            return View(school);
        }

	}
}

Casual Roster Web/Views/School/AddTeacher.cshtml
@model Casual_Roster_Web.Models.TeacherViewModel

@{
    ViewBag.Title = "Request A Temp";
}

@section scripts {
    <script src="/Content/intltelinput/src/intlTelInput.min.js"></script>
    <script>
        $(function() {

            var tmr;

            $('#mobile').on('keyup', updateFields);
            $('body').on('click', '.country-list .country', updateFields); // when country code is changed

            function updateFields() {
                var self = $('#mobile');

                if(tmr) {
                    clearTimeout(tmr);
                }

                // user id of selected mobile
                $('.user-id').val('');

                // remove disabled textboxes
                $('input[type="text"]:not(#mobile)').val('').removeAttr('disabled');

                // delay 1sec to request for mobile info
                tmr = setTimeout(function() {
                    if(!self.val()) return;

                    $.ajax({
                        type: 'post',
                        url: '@Url.Content("~/Teacher/jsonGetMobileInfo")?mobile=' + self.val() + '&countryCode=' + self.intlTelInput("getSelectedCountryData").iso2.toUpperCase(),
                        contentType: 'application/json',
                        success: function(data) {
                            data = data.teacher;
                            $('.user-id').val(data.user_id);

                            for(var key in data) {
                                field = $('#' + key);
                                field.val( data[key] );
                                if(key != 'mobile') {
                                    field.attr('disabled', 'disabled');
                                }
                            }
                        }
                    });

                }, 1000);
            };



            // init intltelinput
            $('#mobile').intlTelInput({
                preferredCountries: ['au', 'ph'],
                utilsScript: "/Content/intltelinput/src/utils.js",
                defaultCountry: $('#mobileCountryCode').val()
            });

            

        }); // end of jquery onready


    </script>
}

@section styles {
    @Styles.Render("~/bundles/intltelinputCss")
}

<div class="col-md-5">

    <h1>Request a Temp</h1>
    <hr />
    @using (Html.BeginForm()) {

        <input type="hidden" class="user-id" name="teacherId" />
        @Html.HiddenFor(x => x.mobileCountryCode)

        <div class="form-group">
            @Html.LabelFor(x => x.mobile )
            @Html.TextBoxFor(x => x.mobile, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.mobile)
        </div>

        <hr />

        <div class="form-group">
            @Html.LabelFor(x => x.firstName )
            @Html.TextBoxFor(x => x.firstName, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.firstName)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.lastName )
            @Html.TextBoxFor(x => x.lastName, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.lastName)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.email )
            @Html.TextBoxFor(x => x.email, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.email)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.postCode )
            @Html.TextBoxFor(x => x.postCode, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.postCode)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.category )
            @Html.TextBoxFor(x => x.category, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.category)
        </div>

        <div class="form-group hidden">
            @Html.LabelFor(x => x.User.username )
            @Html.TextBoxFor(x => x.User.username, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.User.username)
        </div>

        <button type="submit" class="btn btn-primary">Send Request and SMS</button>
    }   
</div>



<div class="col-md-4">
    @if(!ViewData.ModelState.IsValid) {
        <div class="alert alert-danger">
            @Html.ValidationSummary()
        </div>
    }
</div>

Casual Roster Web/Views/School/EditProfile.cshtml
@model Casual_Roster_Web.Models.SchoolViewModel
@{
    ViewBag.Title = "Edit Profile";
}

@section scripts {

    <script src='http://maps.googleapis.com/maps/api/js?v=3&sensor=false&amp;libraries=places'></script>
    @Scripts.Render("~/Content/geocomplete")
    @Scripts.Render("~/bundles/intltelinput")

    <script>
        $(function() {


            // location
            var params = {
                map: '.map'
            };

            var geoMap = $('#formattedAddress').geocomplete(params)

            geoMap.bind("geocode:result", function(event, result){
                if(result) {
                    $('#lat').val( result.geometry.location.lat() );
                    $('#lng').val( result.geometry.location.lng() );
                }
            });

            @if(Model.lat != null && Model.lng != null) {
                <text>
                    $('#formattedAddress').geocomplete("find", "@Model.formattedAddress");
                </text>
            }

        });
    </script>
}

@section styles {
    @Styles.Render("~/Content/select2Css")
    @Styles.Render("~/bundles/intltelinputCss")
}

<div class="row">
    
    @using (Html.BeginForm("EditProfile", "School", FormMethod.Post, new { enctype = "multipart/form-data" } )) {


        <div class="col-md-12 clearfix">

            @if(!ViewData.ModelState.IsValid) {
                <div class="alert alert-danger">
                    @Html.ValidationSummary()
                </div>
            }

            @if(ViewBag.success != null) {
                <div class="alert alert-success">Profile successfully updated</div>
            }

            <h1 class="pull-left">@ViewBag.Title</h1>
            <button type="button" class="pull-right btn btn-success form-submit">Update Profile</button>
        </div>

        @Html.HiddenFor(x => x.mobileCountryCode )
        @Html.HiddenFor(x => x.user_id )

        <div class="clearfix">

            <div class="col-md-3">
                <div class="school-logo" style="background-image: url(@Url.Content("~/Content/uploads")/@(Model.LogoData != null ? Model.LogoData.filename : ""))"></div>
                <div class="form-group">
                    <label>Change logo</label>
                    <input type="file" name="uploadedLogo">
                    <!--<p class="help-block">Example block-level help text here.</p>-->
                </div>
            </div>

            <div class="col-md-5">
                <div class="form-group">
                    @Html.LabelFor(x => x.schoolName )
                    @Html.TextBoxFor(x => x.schoolName, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(x => x.schoolName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.email )
                    @Html.TextBoxFor(x => x.email, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(x => x.email)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.mobile )
                    @Html.TextBoxFor(x => x.mobile, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(x => x.mobile)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.phones )
                    @Html.TextBoxFor(x => x.phones, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(x => x.phones)
                </div>

            </div> 


            <div class="col-md-4">

                <div class="form-group">
                    @Html.LabelFor(x => x.postCode )
                    @Html.TextBoxFor(x => x.postCode, new { @class = "form-control" } )
                    @Html.ValidationMessageFor(x => x.postCode)
                </div>

                <div class="form-group">
                    <label for="formattedAddress">Location</label>
                    @Html.TextBoxFor(x => x.formattedAddress, new { @class = "form-control" } )
                    @Html.HiddenFor(x => x.lat)
                    @Html.HiddenFor(x => x.lng)
                    <div class="panel">
                        <div class="map"></div>
                    </div>
                </div>

            </div>
        </div>


    }
</div>

Casual Roster Web/Views/School/GetStaff.cshtml
@{
    ViewBag.Title = "Get Staff";
}


@section scripts {
    <script>
        $(function() {
            $('.btn-send-request').on('click', function() {
                var selection = $('.check-user-selected:checked');
                var teacherIds = [];
                if(!selection.length) {
                    alert('Please select atleast 1 employer');
                    return;
                }

                selection.each(function() {
                    teacherIds.push($(this).data('user-id'));
                });

                $('.errors').addClass('hidden');
                // make the request
                $.ajax({
                    type: 'post',
                    url: '@Url.Content("~/School/RosterRequest")',
                    contentType: 'application/json',
                    data: JSON.stringify({
                        teacherIds: teacherIds,
                        schoolId: @ViewBag.schoolId,
                        rosterDate: new Date('@ViewBag.requestDate.ToString("yyyy-MM-dd")')
                    }), 
                    success: function(data) {
                        if(data && data.success) {
                            return window.location.href = '@Url.Content("~/School/Roster")';
                        }

                        // something went wrong
                        $('.errors').html(data.errors.join("<br />")).removeClass('hidden');
                    },
                    error: function() {
                        $('.errors').html("Something went wrong.").removeClass('hidden');
                    }
                });

            });
        });
    </script>
}


<div class="col-md-6 col-md-offset-3">
    <div class="alert alert-danger errors hidden">xx</div>
    <div class="text-center">
        <p>
            Please select from the list of available employers for the chosen day
            <h4>@(ViewBag.requestDate.ToString("dddd, MMM dd, yyyy"))</h4>
        </p>
    </div>

    <table class="table table-bordered">
        <tr>
            <th>Name</th>
            <th>Category</th>
            <th>&nbsp;</th>
        </tr>
        @foreach(var teacher in ViewBag.availableTeachers) {
            var profile = teacher.Profile;

            <tr>
                <td>@profile.firstName @profile.lastName</td>
                <td>@profile.category</td>
                <td class="text-center">
                    <input data-user-id="@teacher.id" class="check-user-selected" type="checkbox" />
                </td>
            </tr>
        }

        @if(ViewBag.availableTeachers.Count == 0) {
            <tr>
                <td colspan="3">No current employer available in requested day</td>
            </tr>
        }
    </table>

    <button class="btn btn-primary btn-send-request pull-right">Send SMS to Selected</button>
</div>

Casual Roster Web/Views/School/Profile.cshtml
@model Casual_Roster.School


@{
    ViewBag.Title = Model.Profile.schoolName + " - Casual Roster";
    var profile = Model.Profile;
}


<div class="col-md-3 col-sm-5 col-xs-12">

    @if(Model.Logo != null) {
        <div class="school-logo" style="background-image: url(@Url.Content("~/Content/uploads")/@Model.Logo.Data.filename)"></div>
    }
    
</div>

<div class="col-md-4 col-sm-7 col-xs-12 profile-body">
    @if(ViewBag.CurrentUser != null && ViewBag.CurrentUser.GetProfile().user_id == profile.user_id) {
        <a href="@Url.Content("~/School/EditProfile")" class="btn btn-primary pull-right btn-sm">Edit profile</a>
    }
    <h1>@profile.schoolName</h1>
    <p><label>Name: </label> <b>@profile.schoolName</b></p>
    <p><label>Address: </label> <b>@profile.address</b></p>
    <p><label>Phone(s): </label> <b>@profile.phones</b></p>
    <p><label>Mobile: </label> <b>@profile.mobile</b></p>
    <p><label>Name: </label> <b>@profile.email</b></p>
</div>

<div class="col-md-4 col-sm-12 col-xs-12 map-container">
    @if(profile.Location != null) {
        <p>@profile.Location.formattedAddress</p>
        <img src="https://maps.googleapis.com/maps/api/staticmap?center=@profile.Location.lat,@profile.Location.lng&zoom=14&size=400x300&markers=icon:xxx%7Cshadow:true%7C@(profile.Location.formattedAddress)">
    }

</div>

Casual Roster Web/Views/School/Register.cshtml
@model Casual_Roster_Web.Models.SchoolViewModel


@{
    ViewBag.Title = "Employer Register";
}

@section scripts {
    @Scripts.Render("~/bundles/intltelinput")
}

@section styles {
    @Styles.Render("~/bundles/intltelinputCss")
}

<div class="col-md-5">
    <h1>@ViewBag.Title</h1>
    @using (Html.BeginForm("Register", "School", FormMethod.Post, new { enctype = "multipart/form-data", id = "register-form" } )) {

        @Html.HiddenFor(x => x.mobileCountryCode )

        <div class="form-group">
            <label for="schoolName">School Name</label>
            @Html.TextBoxFor(x => x.schoolName, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.schoolName)
        </div>
        <div class="form-group">
            <label for="address">Address Details</label>
            @Html.TextBoxFor(x => x.address, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.address)
        </div>
        <div class="form-group">
            <label for="phones">Phone(s)</label>
            @Html.TextBoxFor(x => x.phones, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.phones)
        </div>
        <div class="form-group">
            <label for="mobileNumber">Mobile Number</label>
            @Html.TextBoxFor(x => x.mobile, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.mobile)
        </div>
        <div class="form-group">
            <label>Email address</label>
            @Html.TextBoxFor(x => x.email, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.email)
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.postCode )
            @Html.TextBoxFor(x => x.postCode, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.postCode)
        </div>
        <div class="form-group">
            <label>Password</label>
            @Html.PasswordFor(x => x.User.password, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.User.password)
        </div>
        <div class="form-group">
            <label>Repeat Password</label>
            @Html.PasswordFor(x => x.password_repeat, new { @class = "form-control" } )
            @Html.ValidationMessageFor(x => x.password_repeat)
        </div>
        <div class="form-group">
            <label>Logo</label>
            <input type="file" name="uploadedLogo" class="btn btn-default">
            <!--<p class="help-block">Example block-level help text here.</p>-->
        </div>

        <button type="button" class="btn btn-success btn-lg form-submit">Submit</button>
    }
</div>


<div class="col-md-5">
    @if(!ViewData.ModelState.IsValid) {
        <div class="alert alert-danger">
            @Html.ValidationSummary()
        </div>
    }
</div>